<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Caminho Imagem' => '',
    'Categorias' => '',
    'Cep' => '',
    'Clientes' => '',
    'Cors' => '',
    'Cpf Cliente' => '',
    'Create Categoria' => '',
    'Create Cliente' => '',
    'Create Cor' => '',
    'Create Estoque' => '',
    'Create Pedido' => '',
    'Create Produto' => '',
    'Create Tamanho' => '',
    'Create User' => '',
    'Data Hora Cadastro' => '',
    'Data Hora Operacao' => '',
    'Data Hora Pedido' => '',
    'Delete' => '',
    'Descricao' => '',
    'Email' => '',
    'Estado' => '',
    'Estoques' => '',
    'Id Categoria' => '',
    'Id Cor' => '',
    'Id Estoque' => '',
    'Id Pedido' => '',
    'Id Produto' => '',
    'Id Tamanho' => '',
    'Id User' => '',
    'Logradouro' => '',
    'Municipio' => '',
    'Nome' => '',
    'Nome Completo' => '',
    'Numero' => '',
    'Password' => '',
    'Pedidos' => '',
    'Preco' => '',
    'Preco Unitario' => '',
    'Produtos' => '',
    'Quantidade' => '',
    'Quantidade Total' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Subtotal' => '',
    'Tamanhos' => '',
    'The requested page does not exist.' => '',
    'Tipo' => '',
    'Total' => '',
    'Type' => '',
    'Update' => '',
    'Update Categoria: mode' => '',
    'Update Cliente: mode' => '',
    'Update Cor: mode' => '',
    'Update Estoque: mode' => '',
    'Update Pedido: mode' => '',
    'Update Produto: mode' => '',
    'Update Tamanho: mode' => '',
    'Update User: mode' => '',
    'Username' => '',
    'Users' => '',
];
